---
title: "Představení R, Rstudio a Tidyverse"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

R je volně šiřitelný, otevřený programovací jazyk zaměřený specificky na vizualizaci a statistickou analýzu dat.
Jeho počátky sahají do poloviny 90. let minulého století, kdy začal být vytvářen dvěma pracovníky Aucklandské university, Rossem Ihakem a Robertem Gentlemanem. Od té doby se stal stal jedním z nejpopulárnějších jazyků pro analýzu dat a drží se mezi nejpopulárnějšími jazyky vůbec. R je široce využívané jak pro akademický výzkum, tak v komerční i veřejné sféře.

Zatímco funkčnost jiných statistické programů, jako například SPSS nebo Excel, je omezená na předpřipravené nástroje a postupy, možnosti R jsou téměř neomezené. Kromě základních i pokročilých statistických analýz je možné R využít k psaní [knih](https://bookdown.org/), [článků](https://rmarkdown.rstudio.com/), webových stránek (včetně této) nebo [aplikací](https://shiny.rstudio.com/gallery/). R je také využíváno řadou předních statistiků, jejichž práce se týká i sociálněvědního výzkumu.

Cenou za široké možnosti R jsou vyšší nároky na jeho naučení. Na rozdíl od programů s grafickým rozhraním vyžaduje práce s R alespoň základní znalosti programování. Naštěstí dnes již existuje řada zdrojů a komunit, které mohou s tímto problémem pomoci. Pro inspiraci můžeme zmínit blog [R-bloggers](https://www.r-bloggers.com/), skupinu [Rladies](https://rladies.org/) nebo komunitní projekt a podcast [Tidytuesday](https://www.tidytuesday.com/).

# Rstudio

Jedno z věcí, která může práci s R výrazně zjednodušit, je použití vývojářského prostředí, jako je Rstudio.
Rstudio je integrované vývojářské prostředí (*integrated development environmet*), tedy program, který poskytuje funkce nad rámec samotného R.
Jeho cílem je co nejvíce usnadnit každodenní práci.
Nabízí vytváření skriptů, spellcheck, zvýrazňování kódu, automatické hledání chyb, nástroje pro export grafů a mnoho dalšího.
Rstudio není jediným vývojářským prostředí pro (zmínit můžeme například [Vim](https://www.vim.org/scripts/script.php?script_id=2628) nebo [ESS Emacs](https://ess.r-project.org/)), představuje však představuje výbornou rovnováhu mezi výkonem a uživatelskou přívětivostí.


# Tidyverse

Existuje mnoho balíčků a rozšíření, které přináší do R nespočet dalších funkcí nad rámec základní instalace.
[Tidyverse](https://www.tidyverse.org/) je rodinou takovýchto rozšiřujících balíčků.
Balíčky Tidyverse rozšiřují možnosti R zejména v oblastech manipulace a vizualizace dat.
Mnoho úkonů, které se v základním R provádí velmi zdlouhavě nebo krkolomně, jsou v Tidyverse velmi jednoduché.
Další velkou výhodou je, že všechny současti Tidyverse jsou designováni tak, aby si spolu rozuměli a využívali stejnou logiku kódu.
Jednou z nevýhod otevřenosti R je, řada autorů má řadu různých představ o psání počítačového kódu.
To vede k mnoha různým konvencím, které jsou pro běžného uživatele matoucí (např. mají funkce začínat velkým nebo malým písmenem? mají se slova oddělovat potržítkem nebo tečkou?).
Všechny balíčky Tidyverse se drží jednotného principu programování a je proto velice jednoduché jejich funkce kombinovat, bez zbytečných zmatků.
Jedná se tak o další způsob, jak ulehčit ponoření do R.

Je nutné zmínit, že využívání Tidyverse není striktně nutné.
Tidyverse vzniklo dávno po vznikem R a do dneška existuje mnoho uživatelů, pro které představuje základní R (nebo jiné balíčky pro analýzu dat) ideální pracovní prostředí.
Nicméně, stejně jako u Rstudio, Tidyverse představuje rovnováhu mezi uživatelskou přívětivostí a flexibilitou práce.

# Závěrem: Proč nepoužíváme grafická rozhraní?

Na začátku jsme zmínili, že R je programovací jazyk a pro práci s ním je nutné znát základy programování.
Protože je ovšem v R udělat téměř vše, je možné pro něj vytvořit i grafické rozhraní, jako má například SPSS.
Těchto rozhraní je celá řada, nejpopulárnější jsou pravděpodobně [Jamovi](https://www.jamovi.org/) a [R commander](https://www.rcommander.com/).
S využitím těchto rozhraní je možné analýzy "naklikávat" místo psaní programovacího kódu.
Tím se výrazně snižuje obtížnost práce s R. Grafická rozhraní ale mají tři velké slabiny, které dříve nebo později převáží nad jakýmikoliv výhodami:

- **Grafická rozhraní nikdy nepokryjí vše, co R nabízí a co mi potřebujeme**: přestože většina grafických rozhraní obsahuje možnosti pro jednoduchou manipulaci s daty a základní statistické postupy, v žádném z nich nenaklikáte složitější úkony jako cyklické aplikace funkce ("*loopy*") ani nevytvoříte složité psychometrické modely.
Jinak řečeno, pokud se rozhodnee vážněji zabývat kvantitativní analýzou, dříve nebo později se alespoň lehkému programování nevyhneme. A čas ztrávený v grafických rozhraních v tu chvíli nebude příliš přinosný.

- **Grafické rozhraní jsou časově neefektivní**: I kdyby všechny funkce, které pro naši práci potřebujeme, byly obsaženy v některém grafickém rozhraní, práce s nimi by vždy byla pomalejší. Jedním z největších výhod, které počítače přinášejí, je možnost automatizace. Není třeba ručně vytvářet tucet kontingenčních tabulek nebo kontrolovat desítky proměnných, pokud to může počítač udělat za nás. Práce se skriptem umožňuje zadat počítači příkaz a nechat ho, ať ho sám zopakuje na jakkoliv velkém počtu případů, což výrazně šetří čas. Takovéto efektivity s grafickými rozhraními nikdy nedosáhneme.

- **Klikání svádí k nereprodukovatelnosti**: velkou výhodou práce skrze psaní skriptu je, že tento skript slouží jako záznam toho, co se stalo. Kdokoliv, ať už mi sami nebo lidé se zájmem o naši práci, se mohou v budoucnu podívat, jak jsme při analýze postupovali a případně se naší prací inspirovat nebo ji vylepšit. Práce v grafickém rozhraní svádí k rychlému naklikávání, po kterém často nezůstane ani stopa.