---
title: "Data využívaná v kurzu"
---

V kurzu jsou primárně využívaná data o Evropských zemích, získáná z Eurostatu.

Dataset je možné stáhnout v několika formátech:

-   **Comma separated values formát** je ke stažení [zde](https://raw.githubusercontent.com/Sociology-FA-CU/uvod-do-r/master/data/countries.csv) (klikněte pravým tlačítkem a zvolte *Uložit odkaz jako...*/*Save link as...*).

-   **RDS formát** [zde](https://github.com/Sociology-FA-CU/uvod-do-r/raw/master/data/countries.rds).

Data obsahují následující proměnné:

| Jméno proměnné  | Popis                                                             | Zdroj                 |
|-----------------|--------------------------------------|-----------------|
| country         | Jméno země                                                        |                       |
| code            | Dvoumístný ISO kód země                                           |                       |
| gdp             | HDP země v milionech euro (2018)                                  | Eurostat              |
| population      | Populace země k 1. lednu 2018                                     | Eurostat              |
| area            | Celková rozloha země                                              | CIA factbook          |
| eu_member       | Je země členem Evropské unie? (2019)                              | Evropská unie         |
| postsoviet      | Byla země součástí Východního bloku?                              | Wikipedie             |
| life_exp        | Naděje na dožití při narození (2017)                              | OSN                   |
| uni_prc         | Podíl lidí s vysokoškolským vzděláním ve věku 15 až 64 let (2018) | Eurostat              |
| poverty_risk    | Podíl lidí ohrožených chudobou (2017)                             | Eurostat              |
| material_dep    | Podíl lidí s materiální deprivací, 3 nebo méně položek (2017)     | Eurostat              |
| hdi             | Index lidského rozvoje (2018)                                     | OSN                   |
| foundation_date | Datum vzniku/zformování země                                      | Wikipedie             |
| maj_belief      | Největší náboženská skupina v zemi (2018)                         | Pew Researcher Center |
